config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "createmeetings", to: 'meetings#createmeetings'

  resources :users, only: [ :show, :edit, :update] do
    resources :reviews, only: [ :new, :create ]
  end

  resources :availabilities, only: [ :index, :update ]

  resources :meetings, only: [ :show, :index, :update ]

  resources :networks, only: [ :index ]
end

app/views/pages/dashboard.html.erb
<div>
  <div class="display-width">
      <div class="dashboard-cardif" style="text-decoration: none">
        <!-- <i class="fas fa-check-circle"></i>
        <i class="fas fa-times-circle"></i> -->
        <% if @next_meeting %>
          <div class="medium-avatar">
            <%= link_to user_path(@user_next_meeting) do %>
              <%= cl_image_tag(@user_next_meeting.photo.key, classtts: "avatar-large")%>
            <% end %>
          </div>
          <%= link_to meeting_path(@next_meeting), style:"text-decoration: none;" do %>
            <h5>Prochain RDV</h5>
            <div class="user-info">
              <div class="user-details">
                <p style="font-size: 20px; transform: translate(0%, 220%)"><strong><%= @user_next_meeting.first_name%> <%= @user_next_meeting.last_name %></strong></p>
                <p style="transform: translate(0%, 260%); font-size: 17px;"><%= @user_next_meeting.company_name %></p>
                <br>
                <p style="font-size: 17px"><%= @next_meeting.venue_name %></p>
                <p style="font-size: 14px;"><%=  @next_meeting.venue_address %></p>
                <p style="font-size: 14px;"><%= @next_meeting.venue_postcode %> <%= @next_meeting.venue_city.upcase %> </p>
                <%= image_tag 'gps.png', class:"gpsshow", style:"transform: translate(-60%, 10%)" %>
              </div>
            </div>
            <div class="meeting-info">
                <% if @next_meeting.slot.slice(0..-1) == "breakfast" %>
                  <p><%= @next_meeting.date.strftime("%d Mars %Y") %><i class="fas fa-coffee" style="color: white; margin-left: 10px;"></i></p>
                <% elsif @next_meeting.slot.slice(0..-1) == "lunch" %>
                  <p><%= @next_meeting.date.strftime("%d Mars %Y") %><i class="fas fa-hamburger" style="color: white; margin-left: 10px"></i></p>
                <% elsif @next_meeting.slot.slice(0..-1) == "afterwork" %>
                  <p><%= @next_meeting.date.strftime("%d Mars %Y") %><i class="fas fa-beer" style="color: white; margin-left: 10px"></i></p>
                <% end %>
            </div>
          <% end %>
      <% else %>
        <p style="transform: translate(0%, 94%); text-align: center"> Renseignez vos disponbilités afin de rencontrer d'autres entrepreneurs, et créer des synergies</p>
        <div class="d-flex justify-content-center">
          <%= link_to 'Disponibilités', availabilities_path(current_user), class:"btn btndash", style:"margin-top: 80px;" %>
        </div>
      <% end %>
      </div>


<div class= "dash d-flex justify-content-between">

  <% if @most_recent_meeting %>
      <div class="dashboard-card-last d-flex flex-column">
        <div class="globallastmeeting">
          <div class="medium-avatarr">
            <%= link_to user_path(@user_most_recent_meeting) do %>
            <%= cl_image_tag(@user_most_recent_meeting.photo.key, class: "avatar-large")%>
            <% end %>
          </div>
        </div>
          <div class= "lastmeetuser">
             <p><strong><%= @user_most_recent_meeting.first_name%></strong></p>
             <p> <strong><%= @user_most_recent_meeting.last_name %></strong> </p>
              <p style="font-weight: normal;"><%= @user_most_recent_meeting.company_name %></p>
          </div>
        <div>

          <%= link_to new_user_review_path(@most_recent_meeting) do %>
        <%= image_tag 'like2.png', class:"linkedin1", style:"color: blue" %>
        </div>
        <p class= "last-meet text-center pt-2">Dernier RDV</p>
      </div>

  <% end %>
      <div class="dashboard-card-last1 d-flex. flex-column ">
        <div class= "group">
              <%= link_to networks_path do %>
          <%= image_tag 'groupshow.png', class:"groupescount" %>
        </div>
        <div class=" text-center pt-2">
          <div>
           <p> <%= current_user.meetings.count %></p>
          </div>
           <br>
           <br>
           <h5 style="color: #1b262c">RDV</h5>
        </div>
    <% end %>
      </div>
</div>

    <div class="dashboard-cardav text-center d-flex flex-column">
      <div class="availabilities-title">
        <div class="card-title availabilities-header">
          <div class="dispodash">
          <h5>Disponibilités</h56>
          <%= link_to availabilities_path  do %>
            <%= image_tag 'pen.png', class:"pencil-2" %>
          <% end %>
          </div>
        </div>
      </div>
      <div class="dashboard-availabilities">
        <% @availabilities.each do |availability|%>
          <% if availability.breakfast || availability.lunch || availability.afterwork %>
            <div>
              <div class="daysdash">
                <% day = Date::DAYNAMES[availability.week_day][0..1] %>
                <% if day == 'Mo' %>
                  <p><strong><%= day = 'Lu' %></strong></p>
                <% elsif day == "Tu" %>
                  <p><strong><%= day = 'Ma' %></strong></p>
                <% elsif day == "We" %>
                  <p><strong><%= day = 'Me' %></strong></p>
                <% elsif day == "Th" %>
                  <p><strong><%= day = 'Je' %></strong></p>
                <% elsif day == "Fr" %>
                  <p><strong><%= day = 'Ve' %></strong></p>
                <% elsif day == "Sa" %>
                  <p><strong><%= day = 'Sa' %></strong></p>
                <% elsif day == "Su" %>
                  <p><strong><%= day = 'Di' %></strong></p>
                <% end %>
              </div>
              </div>
          <% else %>
            <% d = Date::DAYNAMES[availability.week_day][0..1] %>
            <% if d == 'Mo' %>
              <p><%= d = 'Lu' %></p>
            <% elsif d == "Tu" %>
              <p><%= d = 'Ma' %></p>
            <% elsif d == "We" %>
              <p><%= d = 'Me' %></p>
            <% elsif d == "Th" %>
              <p><%= d = 'Je' %></p>
            <% elsif d == "Fr" %>
              <p><%= d = 'Ve' %></p>
            <% elsif d == "Sa" %>
              <p><%= d = 'Sa' %></p>
            <% elsif d == "Su" %>
              <p><%= d = 'Di' %></p>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="dashboard-availabilities">
        <% @availabilities.each do |availability|%>
          <div class="icon-avail">
            <% if availability.breakfast %>
              <i class="fas fa-coffee icon-active" style="color: white"></i>
            <% else %>
              <i class="fas fa-coffee icon-inactive" style="opacity: 0.2;"></i>
              <!-- <br> -->
            <% end %>
            <% if availability.lunch %>
              <i class="fas fa-hamburger icon-active" style="color: white"></i>
              <!-- <br> -->
            <% else %>
              <i class="fas fa-hamburger icon-inactive" style="opacity: 0.2;"></i>
              <!-- <br> -->
            <% end %>
            <% if availability.afterwork %>
              <i class="fas fa-beer icon-active" style="color: white"></i>
              <!-- <br> -->
            <% else %>
              <i class="fas fa-beer icon-inactive" style="opacity: 0.2;"></i>
              <!-- <br> -->
            <% end %>
            <%#= availability.lunch %>
            <%#= availability.afterwork %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/pages/home.html.erb
<div class="banner w-100" style="height: 100vh; width: 100vh">
  <div class="container py-4">
    <div class="d-flex flex-column align-items-center text-center">
    <br>
    <%= image_tag 'logo_foutaters_V2_2.png', style:"width: 60%; height: 60%" %>
    <br>
    <br>
    <br>
    <br>
    <br>
        <h1 style="border-radius: 20px; padding: 25px">DÉVELOPPE TON RÉSEAU D'ENTREPRENEURS !</h1>
        <br>
        <br>
        <br>
        <br>
        <br>
        <%= link_to raw("Commencer"), dashboard_path, class: "cta-create", style:"border-radius: 20px"%>
    </div>
  </div>
</div>
<!-- <div class="container">
  <div class="text-center pt-2">
    <i class="fas fa-sort-down"></i>
  </div>
  <h2 class="text-center" style="color: #1b262c!important;">Comment ça marche ?</h2>
  <div class="block-points d-flex flex-column align-items-center">

    <div class="cardhome" data-aos="fade-right">
      <p><i class="far fa-calendar-alt"></i></p>
      <h3 class="title-point">1. Vos dispos</h4>
      <p>Renseignez votre profil professionnel, vos centres d'intérêts ainsi que vos disponibilités</p>
    </div>

    <div class="cardhome" data-aos="fade-left">
      <p><i class="fas fa-user-friends"></i></p>
      <h3 class="title-point">2. Votre entrepreneur</h4>
      <p>Foundaters se charge d'organiser chaque semaine un rendez-vous avec un fondateur d'entreprise</p>
    </div>

    <div class="cardhome" data-aos="fade-right">
      <p><i class="fas fa-mug-hot"></i></p>
      <h3 class="title-point">3. Votre rendez-vous</h4>
      <p>Le lieu idéal est choisi automatiquement, à mi chemin entre vous deux, dans un endroit recommandé par notre algorithme.
      </p>
    </div>

    <h3 class="text-center mt-3" style="color: #0096ff !important">Fini la logistique, nous optimisons votre temps !</h3>
    <h3 class="text-center mt-3" style="color: #0096ff !important">Bon networking ;)</h3>
    <%#= link_to raw('<i class="fas fa-caret-right"></i> Je crée mon compte'), new_user_registration_path, class: "cta-create-2"%>
    <br>
  </div>
</div> -->


<!-- ### Caroussel des selfies des users (au cas où...) : -->


<!--
<div class="container text-center mt-3" style="color: #0096ff !important">
  <h4>Rejoint les Foundaters !</h3>
</div>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <#%= image_tag 'selfie_1.jpg', style: "width: 100%;" %>
    </div>
    <div class="carousel-item">
      <#%= image_tag 'selfie_2.jpg', style: "width: 100%;" %>
    </div>
    <div class="carousel-item">
      <#%= image_tag 'selfie_1.jpg', style: "width: 100%;" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
 -->