config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "createmeetings", to: 'meetings#createmeetings'

  resources :users, only: [ :show, :edit, :update] do
    resources :reviews, only: [ :new, :create ]
  end

  resources :availabilities, only: [ :index, :update ]

  resources :meetings, only: [ :show, :index, :update ]

  resources :networks, only: [ :index ]
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
   skip_after_action :verify_policy_scoped, only: :index

  def index
    @availabilities = current_user.availabilities
  end

  def edit
    @user = User.find(params[:id])
    @availability = Availability.find(params[:id])
    authorize @availability
  end

  def update
    @availability = Availability.find(params[:id])
    @availability.user = current_user
    @availability.update(availability_params)
    redirect_to availabilities_path
    authorize @availability
  end

  private

  def availability_params
    params.require(:availability).permit(:week_day, :breakfast, :lunch, :afterwork)
  end

end

app/views/availabilities/index.html.erb
<div class="ava col-sm-12 margin-left-cal">
  <div class="calendar">
    <% @availabilities.sort_by{|d| d[:week_day]}.rotate(1).each do |availability| %>
      <div class='m-2' >
        <%= simple_form_for((availability), remote: true) do |f| %>
          <div class="d-flex direction row">

            <div class="days col-3 mr-4">
              <% f.label day = Date::DAYNAMES[availability.week_day] %>
              <% if day == 'Monday' %>
                <%= 'Lundi' %>
              <% elsif day == 'Tuesday' %>
                <%= 'Mardi' %>
              <% elsif day == 'Wednesday' %>
                <%= 'Mercredi' %>
              <% elsif day == 'Thursday' %>
                <%= 'Jeudi' %>
              <% elsif day == 'Friday' %>
                <%= 'Vendredi' %>
              <% elsif day == 'Saturday' %>
                <%= 'Samedi' %>
              <% elsif day == 'Sunday' %>
                <%= 'Dimanche' %>
              <% end %>
            </div>

            <div class="tabs selected ml-2 <%= availability.breakfast? ? 'touch-choice' : 'choice' %>">
              <i class="fas fa-coffee"></i>
              <div style="display: none">
                <%= f.input :breakfast %>
              </div>
            </div>

            <div class="tabs selected ml-2 <%= availability.lunch? ? 'touch-choice' : 'choice' %>">
              <i class="fas fa-hamburger"></i>
              <div style="display: none">
                <%= f.input :lunch %>
              </div>
            </div>


            <div class="tabs selected ml-2 <%= availability.afterwork? ? 'touch-choice' : 'choice' %>">
              <i class="fas fa-beer"></i>
              <div style="display: none">
                <%= f.input :afterwork%>
              </div>
            </div>

            <div style="display: none">
              <%= f.submit %>
            </div>

          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="divdash">
  <%= link_to 'GENERER UN RDV', createmeetings_path, class:"btn btndash" %>
</div>